export const SYMPTOM_CATEGORIES = [
  {
    id: 'head',
    label: 'Head',
    emoji: '🤕',
    items: [
      { id: 'headache', label: 'Headache', emoji: '🔨' },
      { id: 'migraines', label: 'Migraines', emoji: '🧠' },
      { id: 'dizziness', label: 'Dizziness', emoji: '🌀' },
      { id: 'acne', label: 'Acne', emoji: '🍓' },
      { id: 'hectic_fever', label: 'Hectic fever', emoji: '🌡️' },
    ],
  },
  {
    id: 'body',
    label: 'Body',
    emoji: '💪',
    items: [
      { id: 'neck_aches', label: 'Neck aches', emoji: '🦴' },
      { id: 'shoulder_aches', label: 'Shoulder aches', emoji: '💪' },
      { id: 'tender_breast', label: 'Tender Breasts', emoji: '🎯' },
      { id: 'breast_sensitivity', label: 'Breast sensitivity', emoji: '➕' },
      { id: 'backaches', label: 'Backaches', emoji: '🦴' },
      { id: 'low_back_pain', label: 'Low back pain', emoji: '⚡' },
      { id: 'body_aches', label: 'Body aches', emoji: '🤕' },
      { id: 'muscle_pain', label: 'Muscle pain', emoji: '💪' },
      { id: 'influenza', label: 'Influenza', emoji: '🤧' },
      { id: 'illness', label: 'Illness', emoji: '🤒' },
      { id: 'cramps', label: 'Cramps', emoji: '⚡' },
      { id: 'chills', label: 'Chills', emoji: '🥶' },
      { id: 'itchiness', label: 'Itchiness', emoji: '🫳' },
      { id: 'rashes', label: 'Rashes', emoji: '🔴' },
      { id: 'night_sweats', label: 'Night sweats', emoji: '💦' },
      { id: 'hot_flashes', label: 'Hot flashes', emoji: '🔥' },
      { id: 'weight_gain', label: 'Weight gain', emoji: '⚖️' },
      { id: 'pms', label: 'PMS', emoji: '😣' },
    ],
  },
  {
    id: 'cervix',
    label: 'Cervix',
    emoji: '🌸',
    items: [
      { id: 'pelvic_pain', label: 'Pelvic pain', emoji: '⚡' },
      { id: 'cervical_firmness', label: 'Cervical firmness', emoji: '🔘' },
      { id: 'cervical_opening', label: 'Cervical opening', emoji: '⭕' },
      { id: 'cervical_mucus', label: 'Cervical mucus', emoji: '💧' },
      { id: 'flow', label: 'Flow', emoji: '🩸' },
      { id: 'spotting', label: 'Spotting', emoji: '🔴' },
      { id: 'irritation', label: 'Irritation', emoji: '😖' },
    ],
  },
  {
    id: 'fluid',
    label: 'Fluid',
    emoji: '💧',
    items: [
      { id: 'dry', label: 'Dry', emoji: '🏜️' },
      { id: 'sticky', label: 'Sticky', emoji: '🍯' },
      { id: 'creamy', label: 'Creamy', emoji: '🥛' },
      { id: 'watery', label: 'Watery', emoji: '💧' },
      { id: 'egg_white', label: 'Egg white', emoji: '🥚' },
      { id: 'cottage_cheese', label: 'Cottage-cheese', emoji: '🧀' },
      { id: 'green', label: 'Green', emoji: '🟢' },
      { id: 'blood_foul', label: 'With blood / foul-smelling', emoji: '⚠️' },
    ],
  },
  {
    id: 'abdomen',
    label: 'Abdomen',
    emoji: '🫃',
    items: [
      { id: 'bloating', label: 'Bloating', emoji: '🫧' },
      { id: 'constipation', label: 'Constipation', emoji: '🚫' },
      { id: 'diarrhea', label: 'Diarrhea', emoji: '💨' },
      { id: 'nausea', label: 'Nausea', emoji: '🤢' },
      { id: 'abdominal_cramps', label: 'Abdominal cramps', emoji: '⚡' },
      { id: 'gas', label: 'Gas', emoji: '💨' },
      { id: 'hunger', label: 'Hunger', emoji: '🍽️' },
      { id: 'cravings', label: 'Cravings', emoji: '🍫' },
      { id: 'ovulation_pain', label: 'Ovulation pain', emoji: '✨' },
    ],
  },
  {
    id: 'mental',
    label: 'Mental',
    emoji: '🧠',
    items: [
      { id: 'anxiety', label: 'Anxiety', emoji: '😰' },
      { id: 'insomnia', label: 'Insomnia', emoji: '🌙' },
      { id: 'stress', label: 'Stress', emoji: '😫' },
      { id: 'moodiness', label: 'Moodiness', emoji: '🌊' },
      { id: 'tension', label: 'Tension', emoji: '😬' },
      { id: 'irritability', label: 'Irritability', emoji: '😤' },
      { id: 'unable_concentrate', label: 'Unable to concentrate', emoji: '😵' },
      { id: 'fatigue', label: 'Fatigue', emoji: '😴' },
      { id: 'confusion', label: 'Confusion', emoji: '😕' },
    ],
  },
]